-- 코드를 입력하세요
SELECT DISTINCT C1.CART_ID
FROM (SELECT CART_ID 
      FROM CART_PRODUCTS 
      WHERE NAME = "Yogurt") AS C1
INNER JOIN (SELECT CART_ID 
            FROM CART_PRODUCTS 
            WHERE NAME = "Milk") AS C2 
ON C1.CART_ID = C2.CART_ID