SELECT
    COUNT(*) AS FISH_COUNT,
    fni.FISH_NAME
FROM
    FISH_INFO AS fi
INNER JOIN FISH_NAME_INFO AS fni
    ON fi.FISH_TYPE = fni.FISH_TYPE
GROUP BY
    fni.FISH_TYPE, fni.FISH_NAME
ORDER BY
    FISH_COUNT DESC;