-- 코드를 입력하세요
SELECT
    FP.PRODUCT_ID,
    FP.PRODUCT_NAME,
    FP.PRICE*FO.TOTAL_AMOUNT as TOTAL_SALES
FROM
   FOOD_PRODUCT AS FP
JOIN 
    (SELECT
        PRODUCT_ID,
        SUM(AMOUNT) AS TOTAL_AMOUNT
     FROM 
        FOOD_ORDER
     WHERE
        DATE_FORMAT(PRODUCE_DATE, '%Y-%m') = '2022-05'
     GROUP BY
        PRODUCT_ID
        ) AS FO
ON
    FP.PRODUCT_ID = FO.PRODUCT_ID
ORDER BY
    TOTAL_SALES DESC,
    PRODUCT_ID ASC;