-- 코드를 작성해주세요
SELECT
    HD.DEPT_ID,
    HD.DEPT_NAME_EN,
    ROUND(HE.AVG_SAL, 0) AS AVG_SAL
FROM
    HR_DEPARTMENT AS HD
JOIN 
    (SELECT
        DEPT_ID,
        AVG(SAL) AS AVG_SAL
    FROM 
        HR_EMPLOYEES
    GROUP BY
        DEPT_ID) AS HE
ON 
    HD.DEPT_ID = HE.DEPT_ID
ORDER BY
    HE.AVG_SAL DESC;