SELECT 
    B.CATEGORY,
    SUM(BS.SALES) AS TOTAL_SALES
FROM 
   BOOK_SALES AS BS
JOIN
    BOOK AS B ON 
    BS.BOOK_ID = B.BOOK_ID
WHERE
    DATE_FORMAT(BS.SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY
    B.CATEGORY
ORDER BY
    B.CATEGORY;